<?php
	/*---------------------OOPS----------------------------
		OOPS STANDS FOR OBJECT ORIENTED PROGRAMMING STRUCTURE.
		IT IS THE COLLECTION OF VARIOUS COMPONENTS WHICH ARE GIVEN BELOW:
		
		>>>>>CLASS:
					A CLASS IS A COLLECTION OF OBJECTS.
		>>>>>OBJECT:
					AN OBJECT IS AN INSTANCE OF A CLASS.
		>>>>>ENCAPSULATION:
					ENCAPSULATION IS USED TO WRAP-UP A DATA IN A CONTAINER.
		>>>>>ABSTRACTION:
					HIDDING OF DATA OR ABSTRACTION IS USED TO SET ACCESS LEVEL OF A MEMBER.
		>>>>>POLYMORPHISM:
					WHEN A FUNCTION WITH SAME NAME PERFORM MULTIPLE TASKS THIS FEATURE IS KNOWN AS POLYMORPHISM.
				CAN BE CATEGORISED INTO TWO PARTS.
				******* RUN TIME POLYMORPHISM (overriding)
				******* COMPILE TIME POLYMORPHISM (overloading)
		>>>>>INHERITANCE:
					INHERITANCE USED TO EXTEND PROPERTIES OF A CLASS TO ANOTHER CLASS.
					INHERITANCE IS OF 5 TYPES BUT PHP CAN SUPPORT ONLY 3 TYPES OS INHERITANCE.
					###### SINGLE LEVEL
					###### MULTI LEVEL
					###### HIERARICHAL
					###### MULTIPLE 						   : NOT SUPPORTED
					###### HYBIRD (INHERITANCE OF INHERITANCE) : NOT SUPPORTED
?>